/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTRO_H_RPCGEN
#define _REGISTRO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME 256

typedef char *rpc_string;

struct imprimir_1_argument {
	rpc_string op;
	rpc_string usuario;
	rpc_string fichero;
};
typedef struct imprimir_1_argument imprimir_1_argument;

#define REGISTRO_PROG 0x20522125
#define REGISTRO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR 1
extern  enum clnt_stat imprimir_1(rpc_string , rpc_string , rpc_string , void *, CLIENT *);
extern  bool_t imprimir_1_svc(rpc_string , rpc_string , rpc_string , void *, struct svc_req *);
extern int registro_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR 1
extern  enum clnt_stat imprimir_1();
extern  bool_t imprimir_1_svc();
extern int registro_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_string (XDR *, rpc_string*);
extern  bool_t xdr_imprimir_1_argument (XDR *, imprimir_1_argument*);

#else /* K&R C */
extern bool_t xdr_rpc_string ();
extern bool_t xdr_imprimir_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTRO_H_RPCGEN */
