/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "registro.h"

bool_t
xdr_rpc_string (XDR *xdrs, rpc_string *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_NAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_imprimir_1_argument (XDR *xdrs, imprimir_1_argument *objp)
{
	 if (!xdr_rpc_string (xdrs, &objp->op))
		 return FALSE;
	 if (!xdr_rpc_string (xdrs, &objp->usuario))
		 return FALSE;
	 if (!xdr_rpc_string (xdrs, &objp->fichero))
		 return FALSE;
	return TRUE;
}
