/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registro.h"
#include <stdio.h>
#include <string.h>

bool_t
imprimir_1_svc(rpc_string op, rpc_string usuario, rpc_string fichero, void *result,  struct svc_req *rqstp)
{
	bool_t retval;

	if (strcmp(op, "SENDATTACH") != 0) {
		printf("%s		%s\n", usuario, op);
	} else {
		printf("%s		%s	%s\n", usuario, op, fichero);
	}

	retval = TRUE;

	return retval;
}

int
registro_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
