/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "registro.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
imprimir_1(rpc_string op, rpc_string usuario, rpc_string fichero, void *clnt_res,  CLIENT *clnt)
{
	imprimir_1_argument arg;
	arg.op = op;
	arg.usuario = usuario;
	arg.fichero = fichero;
	return (clnt_call (clnt, IMPRIMIR, (xdrproc_t) xdr_imprimir_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
